on:
  push:
    branches: [ master ]
    paths: [ 'Cargo.toml' ]
  workflow_dispatch: {}

name: Release

jobs:
  publish:
    name: Pulish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish
